version: "3.8"

services:
  querycrafter:
    image: jpazarzis/querycrafter:0.1
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVICE_PORT=${INTERNAL_FRONT_END_PORT}
      - LLM_MODEL=${LLM_MODEL}
    ports:
      - "${EXTERNAL_FRONT_END_PORT}:${INTERNAL_FRONT_END_PORT}"
